import Foundation
import Mockable

/// Repository protocol for storing provider settings (e.g., isEnabled state).
/// Tests use MockProviderSettingsRepository (generated by @Mockable).
/// App uses UserDefaultsProviderSettingsRepository.
@Mockable
public protocol ProviderSettingsRepository: Sendable {
    /// Gets the enabled state for a provider (defaults to true if not set)
    func isEnabled(forProvider id: String) -> Bool

    /// Sets the enabled state for a provider
    func setEnabled(_ enabled: Bool, forProvider id: String)

    /// Gets the enabled state for a provider with a custom default
    func isEnabled(forProvider id: String, defaultValue: Bool) -> Bool

    /// Gets the custom card URL for a provider (nil if not set)
    func customCardURL(forProvider id: String) -> String?

    /// Sets the custom card URL for a provider (empty string or nil to remove)
    func setCustomCardURL(_ url: String?, forProvider id: String)
}

/// Bedrock-specific settings repository, extending base ProviderSettingsRepository.
/// Stores AWS profile name (not credentials) and region configuration.
/// Tests can use UserDefaultsProviderSettingsRepository with test UserDefaults.
/// App uses UserDefaultsProviderSettingsRepository.
public protocol BedrockSettingsRepository: ProviderSettingsRepository {
    // MARK: - AWS Profile

    /// Gets the AWS profile name (empty = use default profile)
    func awsProfileName() -> String

    /// Sets the AWS profile name
    func setAWSProfileName(_ name: String)

    // MARK: - Regions

    /// Gets the list of AWS regions to monitor for Bedrock usage
    func bedrockRegions() -> [String]

    /// Sets the list of AWS regions to monitor
    func setBedrockRegions(_ regions: [String])

    // MARK: - Budget

    /// Gets the daily budget for quota calculations (nil = no budget set)
    func bedrockDailyBudget() -> Decimal?

    /// Sets the daily budget for quota calculations
    func setBedrockDailyBudget(_ amount: Decimal?)
}

/// Claude-specific settings repository, extending base ProviderSettingsRepository.
/// Includes configuration for probe mode (CLI vs API).
/// Tests can use UserDefaultsProviderSettingsRepository with test UserDefaults.
/// App uses UserDefaultsProviderSettingsRepository.
public protocol ClaudeSettingsRepository: ProviderSettingsRepository {
    /// Gets the probe mode for Claude (CLI or API)
    func claudeProbeMode() -> ClaudeProbeMode

    /// Sets the probe mode for Claude
    func setClaudeProbeMode(_ mode: ClaudeProbeMode)

    /// Whether to fall back to the CLI probe when the OAuth API probe is unavailable.
    /// Defaults to true. Disable to prevent `claude /usage` from running in API mode.
    func claudeCliFallbackEnabled() -> Bool

    /// Sets whether CLI fallback is enabled in API mode
    func setClaudeCliFallbackEnabled(_ enabled: Bool)
}

/// Codex-specific settings repository, extending base ProviderSettingsRepository.
/// Includes configuration for probe mode (RPC vs API).
/// Tests can use UserDefaultsProviderSettingsRepository with test UserDefaults.
/// App uses UserDefaultsProviderSettingsRepository.
public protocol CodexSettingsRepository: ProviderSettingsRepository {
    /// Gets the probe mode for Codex (RPC or API)
    func codexProbeMode() -> CodexProbeMode

    /// Sets the probe mode for Codex
    func setCodexProbeMode(_ mode: CodexProbeMode)
}

// MARK: - Default Implementation

public extension ProviderSettingsRepository {
    /// Default implementation that uses `true` as the default value
    func isEnabled(forProvider id: String) -> Bool {
        isEnabled(forProvider: id, defaultValue: true)
    }
}
