import Foundation
import Mockable

/// Repository protocol for storing provider settings (e.g., isEnabled state).
/// Tests use MockProviderSettingsRepository (generated by @Mockable).
/// App uses UserDefaultsProviderSettingsRepository.
@Mockable
public protocol ProviderSettingsRepository: Sendable {
    /// Gets the enabled state for a provider (defaults to true if not set)
    func isEnabled(forProvider id: String) -> Bool

    /// Sets the enabled state for a provider
    func setEnabled(_ enabled: Bool, forProvider id: String)

    /// Gets the enabled state for a provider with a custom default
    func isEnabled(forProvider id: String, defaultValue: Bool) -> Bool
}

/// Codex-specific settings repository, extending base ProviderSettingsRepository.
/// Includes configuration for probe mode (RPC vs API).
/// Tests can use UserDefaultsProviderSettingsRepository with test UserDefaults.
/// App uses UserDefaultsProviderSettingsRepository.
public protocol CodexSettingsRepository: ProviderSettingsRepository {
    /// Gets the probe mode for Codex (RPC or API)
    func codexProbeMode() -> CodexProbeMode

    /// Sets the probe mode for Codex
    func setCodexProbeMode(_ mode: CodexProbeMode)
}

// MARK: - Default Implementation

public extension ProviderSettingsRepository {
    /// Default implementation that uses `true` as the default value
    func isEnabled(forProvider id: String) -> Bool {
        isEnabled(forProvider: id, defaultValue: true)
    }
}
